aaa: 张三

spring:
  application:
    name: blogsadmin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${env.mysql.username:root}
    password: ${env.mysql.password:root}
    url: jdbc:mysql://${env.mysql.host:127.0.0.1}:${env.mysql.port:3306}/${ENV_MYSQL_DATABASE:open_blog}?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-init-sql: SET NAMES utf8mb4;SET time_zone = '+8:00';
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
  data:
    redis:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB #单个文件大小
      max-request-size: 100MB #总文件大小
  profiles:
    active: ${ENV_PROFILES_ACTIVE:prod}
#开发阶段使用
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
logging:
  # 指定配置文件，默认classpath:logback-spring.xml输出到控制台
  config: ${ENV_LOG_CONFIG:classpath:logback-spring.xml}


open:
  blog:
    sys:
      expireTime: 4
      secretKey: abcdefg
      needLogin: true
      front-url: http://blogs-pre.office.blog.com/#
      deploy-callback-url: http://apiblogs.office.blog.com/com.git.blog.api/deploy/callback
      jen-kins-username: ${JENKINS_USERNAME:authorZhao}
      jen-kins-password: ${JENKINS_PASSWORD:xxxxxx}
    wx:
      wx-app-id:
      wx-app-secret:
      redirect-login-page: ${LOGIN_CALLBACK:}
      # 这个可能要改，这个表示的是新用户扫码的页面，需要调整
      redirect-user-page: /my/info
      globe-wx-work-key:
    ding:
      globe-ding-talk-token:
      globe-ding-talk-secret:
      # 配置地址
    config:
      config-url: http://rc.office.blog.com/spi/rc
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false



---
#prod环境
env:
  mysql:
    username: dev
    password: dev

spring:
  profiles: prod

open:
  blog:
    sys:
      expireTime: 4
      secretKey: abcdefg
      needLogin: true
      front-url: http://blogs-pre.office.blog.com/#
      deploy-callback-url: http://apiblogs.office.blog.com/com.git.blog.api/deploy/callback
      jen-kins-username: ${JENKINS_USERNAME:authorZhao}
      jen-kins-password: ${JENKINS_PASSWORD:xxxxxx}
      imgHost: http://opadmin.pingyuanren.top/
      hexoPath: /usr/local/src/hexo
    wx:
      wx-app-id:
      wx-app-secret:
      redirect-login-page: ${LOGIN_CALLBACK:}
      # 这个可能要改，这个表示的是新用户扫码的页面，需要调整
      redirect-user-page: /my/info
      globe-wx-work-key: cdebd701-fd69-4652-8b83-d1044d9eaecd
    ding:
      globe-ding-talk-token:
      globe-ding-talk-secret:
      # 配置地址
    config:
      config-url: http://rc.office.blog.com/spi/rc
